// Code generated by MockGen. DO NOT EDIT.
// Source: internal/delivery/ws/ws-manager.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	forms "quickflow/internal/delivery/forms"
	models "quickflow/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	websocket "github.com/gorilla/websocket"
)

// MockIWebSocketManager is a mock of IWebSocketManager interface.
type MockIWebSocketManager struct {
	ctrl     *gomock.Controller
	recorder *MockIWebSocketManagerMockRecorder
}

// MockIWebSocketManagerMockRecorder is the mock recorder for MockIWebSocketManager.
type MockIWebSocketManagerMockRecorder struct {
	mock *MockIWebSocketManager
}

// NewMockIWebSocketManager creates a new mock instance.
func NewMockIWebSocketManager(ctrl *gomock.Controller) *MockIWebSocketManager {
	mock := &MockIWebSocketManager{ctrl: ctrl}
	mock.recorder = &MockIWebSocketManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIWebSocketManager) EXPECT() *MockIWebSocketManagerMockRecorder {
	return m.recorder
}

// HandlePing mocks base method.
func (m *MockIWebSocketManager) HandlePing(conn *websocket.Conn) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandlePing", conn)
}

// HandlePing indicates an expected call of HandlePing.
func (mr *MockIWebSocketManagerMockRecorder) HandlePing(conn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandlePing", reflect.TypeOf((*MockIWebSocketManager)(nil).HandlePing), conn)
}

// IsConnected mocks base method.
func (m *MockIWebSocketManager) IsConnected(userId uuid.UUID) (*websocket.Conn, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsConnected", userId)
	ret0, _ := ret[0].(*websocket.Conn)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// IsConnected indicates an expected call of IsConnected.
func (mr *MockIWebSocketManagerMockRecorder) IsConnected(userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsConnected", reflect.TypeOf((*MockIWebSocketManager)(nil).IsConnected), userId)
}

// SendMessageToChat mocks base method.
func (m *MockIWebSocketManager) SendMessageToChat(ctx context.Context, message models.Message, publicSenderInfo models.PublicUserInfo, chatParticipants []models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessageToChat", ctx, message, publicSenderInfo, chatParticipants)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessageToChat indicates an expected call of SendMessageToChat.
func (mr *MockIWebSocketManagerMockRecorder) SendMessageToChat(ctx, message, publicSenderInfo, chatParticipants interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessageToChat", reflect.TypeOf((*MockIWebSocketManager)(nil).SendMessageToChat), ctx, message, publicSenderInfo, chatParticipants)
}

// SendMessageToUser mocks base method.
func (m *MockIWebSocketManager) SendMessageToUser(ctx context.Context, userId uuid.UUID, message forms.MessageOut) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessageToUser", ctx, userId, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessageToUser indicates an expected call of SendMessageToUser.
func (mr *MockIWebSocketManagerMockRecorder) SendMessageToUser(ctx, userId, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessageToUser", reflect.TypeOf((*MockIWebSocketManager)(nil).SendMessageToUser), ctx, userId, message)
}
