package http

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"quickflow/pkg/logger"
	"time"

	"github.com/google/uuid"

	"quickflow/config"
	"quickflow/internal/delivery/forms"
	"quickflow/internal/models"
	http2 "quickflow/utils/http"
)

type PostUseCase interface {
	FetchFeed(ctx context.Context, user models.User, numPosts int, timestamp time.Time) ([]models.Post, error)
	AddPost(ctx context.Context, post models.Post) error
	DeletePost(ctx context.Context, user models.User, postId uuid.UUID) error
}

type FeedHandler struct {
	postUseCase    PostUseCase
	profileUseCase ProfileUseCase
}

// NewFeedHandler creates new feed handler.
func NewFeedHandler(postUseCase PostUseCase, profileUseCase ProfileUseCase) *FeedHandler {
	return &FeedHandler{
		postUseCase:    postUseCase,
		profileUseCase: profileUseCase,
	}
}

// GetFeed возвращает ленту постов
// @Summary Получить ленту
// @Description Возвращает список постов, опубликованных до указанного времени
// @Tags Feed
// @Produce json
// @Param posts_count query int true "Количество постов"
// @Param ts query string false "Временная метка"
// @Success 200 {array} forms.PostOut "Список постов"
// @Failure 400 {object} forms.ErrorForm "Некорректные данные"
// @Failure 500 {object} forms.ErrorForm "Ошибка сервера"
// @Router /api/feed [get]
func (f *FeedHandler) GetFeed(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	// extracting user from context
	user, ok := ctx.Value("user").(models.User)
	if !ok {
		logger.Error(ctx, "Failed to get user from context while fetching feed")
		http2.WriteJSONError(w, "Failed to get user from context", http.StatusInternalServerError)
		return
	}
	logger.Info(ctx, fmt.Sprintf("User %s requested feed", user.Username))

	// parsing JSON
	var feedForm forms.FeedForm
	err := feedForm.GetParams(r.URL.Query())
	if err != nil {
		logger.Error(ctx, fmt.Sprintf("Failed to parse query params: %v", err))
		http2.WriteJSONError(w, "Failed to parse query params", http.StatusBadRequest)
		return
	}

	ts, err := time.Parse(config.TimeStampLayout, feedForm.Ts)
	if err != nil {
		ts = time.Now()
	}

	logger.Info(ctx, fmt.Sprintf("Fetching feed for user %s with %d posts with timestamp %v (autogenerated: %t)", user.Username, feedForm.Posts, ts, err != nil))
	posts, err := f.postUseCase.FetchFeed(ctx, user, feedForm.Posts, ts)
	if err != nil {
		logger.Error(ctx, fmt.Sprintf("Failed to fetch feed: %v", err))
		http2.WriteJSONError(w, "Failed to load feed", http.StatusInternalServerError)
		return
	}

	logger.Info(ctx, fmt.Sprintf("Fetched %d posts for user %s", len(posts), user.Username))
	var postsOut []forms.PostOut
	var authors []uuid.UUID
	for _, post := range posts {
		var postOut forms.PostOut
		postOut.FromPost(post)
		postsOut = append(postsOut, postOut)
		authors = append(authors, post.CreatorId)
	}

	// Fetching authors
	publicAuthorsInfo, err := f.profileUseCase.GetPublicUsersInfo(ctx, authors)
	for i := range postsOut {
		postsOut[i].Creator = forms.PublicUserInfoToOut(publicAuthorsInfo[authors[i]])
	}

	w.Header().Set("Content-Type", "application/json")
	err = json.NewEncoder(w).Encode(postsOut)
	if err != nil {
		logger.Error(ctx, fmt.Sprintf("Failed to encode feed: %s", err.Error()))
		http2.WriteJSONError(w, "Failed to encode feed", http.StatusInternalServerError)
		return
	}
}
