package http

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/google/uuid"

	time2 "quickflow/config/time"
	"quickflow/gateway/internal/delivery/forms"
	errors2 "quickflow/gateway/internal/errors"
	http2 "quickflow/gateway/utils/http"
	"quickflow/shared/logger"
	"quickflow/shared/models"
)

type ChatUseCase interface {
	GetChatParticipants(ctx context.Context, chatId uuid.UUID) ([]uuid.UUID, error)
	GetUserChats(ctx context.Context, userId uuid.UUID, numChats int, ts time.Time) ([]models.Chat, error)
	GetPrivateChat(ctx context.Context, userId1, userId2 uuid.UUID) (*models.Chat, error)
	DeleteChat(ctx context.Context, chatId uuid.UUID) error
	GetChat(ctx context.Context, chatId uuid.UUID) (*models.Chat, error)
	JoinChat(ctx context.Context, chatId, userId uuid.UUID) error
	LeaveChat(ctx context.Context, chatId, userId uuid.UUID) error
}

type ChatHandler struct {
	chatUseCase    ChatUseCase
	profileUseCase ProfileUseCase
	connService    IWebSocketConnectionManager
}

func NewChatHandler(chatUseCase ChatUseCase, profileUseCase ProfileUseCase, connService IWebSocketConnectionManager) *ChatHandler {
	return &ChatHandler{
		chatUseCase:    chatUseCase,
		profileUseCase: profileUseCase,
		connService:    connService,
	}
}

// GetUserChats godoc
// @Summary Get user chats
// @Description Get user chats
// @Tags Chats
// @Accept json
// @Produce json
// @Param ts query string false "Timestamp"
// @Param chats_count query int true "Number of chats"
// @Success 200 {array} forms.ChatOut "List of chats"
// @Failure 400 {object} forms.ErrorForm "Invalid data"
// @Failure 403 {object} forms.ErrorForm "User is not a participant in the chat"
// @Failure 500 {object} forms.ErrorForm "Server error"
// @Router /api/chats [get]
func (c *ChatHandler) GetUserChats(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	logger.Info(ctx, "Got GetUserChats request")

	user, ok := ctx.Value("user").(models.User)
	if !ok {
		logger.Error(ctx, "Failed to get user from context while fetching messages")
		http2.WriteJSONError(w, errors2.New(errors2.InternalErrorCode, "Failed to get user from context", http.StatusInternalServerError))
		return
	}

	var chatForm forms.GetChatsForm
	err := chatForm.GetParams(r.URL.Query())
	if err != nil {
		logger.Error(ctx, fmt.Sprintf("Failed to parse query params: %v", err))
		http2.WriteJSONError(w, errors2.New("BAD_REQUEST", "Failed to parse query params", http.StatusBadRequest))
		return
	}

	logger.Info(ctx, fmt.Sprintf("Fetching feed for user %s with %d posts with timestamp %v (autogenerated: %t)",
		user.Username, chatForm.ChatsCount, chatForm.Ts, !r.URL.Query().Has("ts")))

	chats, err := c.chatUseCase.GetUserChats(ctx, user.Id, chatForm.ChatsCount, chatForm.Ts)
	if err != nil {
		logger.Error(ctx, fmt.Sprintf("Failed to fetch chats: %v", err))
		http2.WriteJSONError(w, err)
		return
	}

	logger.Info(ctx, fmt.Sprintf("Fetched %d chats for user %s", len(chats), user.Username))

	var senders []uuid.UUID
	for _, chat := range chats {
		senders = append(senders, chat.LastMessage.SenderID)
	}

	var publicInfos []models.PublicUserInfo
	if len(senders) != 0 {
		publicInfos, err = c.profileUseCase.GetPublicUsersInfo(ctx, senders)
		if err != nil {
			logger.Error(ctx, fmt.Sprintf("Error while fetching last messages users info: %v", err))
			http2.WriteJSONError(w, err)
			return
		}
	}
	lastMessageSenderInfo := make(map[uuid.UUID]models.PublicUserInfo)
	for _, info := range publicInfos {
		lastMessageSenderInfo[info.Id] = info
	}

	// Convert chats to output format
	var (
		privateChatsOnlineStatus = make(map[uuid.UUID]forms.PrivateChatInfo)
		isOnline                 bool
		username                 string
		lastSeen                 time.Time
	)
	for _, chat := range chats {
		if chat.Type != models.ChatTypePrivate {
			continue
		}

		if chat.LastMessage.ID != uuid.Nil && chat.LastMessage.SenderID != user.Id {
			_, isOnline = c.connService.IsConnected(chat.LastMessage.SenderID)
			lastSeen = lastMessageSenderInfo[chat.LastMessage.SenderID].LastSeen
			username = lastMessageSenderInfo[chat.LastMessage.SenderID].Username
		} else {
			// Get the other participant's ID
			otherUser, err := c.getOtherPrivateChatParticipant(ctx, chat.ID, user.Id)
			if err != nil {
				logger.Error(ctx, fmt.Sprintf("Failed to get other participant: %v", err))
				http2.WriteJSONError(w, err)
				return
			}
			_, isOnline = c.connService.IsConnected(otherUser)

			otherUserInfo, err := c.profileUseCase.GetPublicUserInfo(ctx, otherUser)
			if err != nil {
				logger.Error(ctx, fmt.Sprintf("Failed to get other user info: %v", err))
				http2.WriteJSONError(w, err)
				return
			}
			lastSeen = otherUserInfo.LastSeen
			username = otherUserInfo.Username
		}

		privateChatsOnlineStatus[chat.ID] = forms.PrivateChatInfo{
			Username: username,
			Activity: forms.Activity{IsOnline: isOnline, LastSeen: lastSeen.Format(time2.TimeStampLayout)},
		}
	}

	chatsOut := forms.ToChatsOut(chats, lastMessageSenderInfo, privateChatsOnlineStatus)
	w.Header().Set("Content-Type", "application/json")
	err = json.NewEncoder(w).Encode(chatsOut)
	if err != nil {
		logger.Error(ctx, fmt.Sprintf("Failed to encode chats: %s", err.Error()))
		http2.WriteJSONError(w, errors2.New(errors2.InternalErrorCode, "Failed to encode chats", http.StatusInternalServerError))
		return
	}
}

func (c *ChatHandler) getOtherPrivateChatParticipant(ctx context.Context, chatId uuid.UUID, userId uuid.UUID) (uuid.UUID, error) {
	participants, err := c.chatUseCase.GetChatParticipants(ctx, chatId)
	if err != nil {
		err := errors2.FromGRPCError(err)
		logger.Error(ctx, fmt.Sprintf("Failed to get chat participants: %v", err))
		return uuid.Nil, err
	}

	for _, participant := range participants {
		if participant != userId {
			return participant, nil
		}
	}
	return uuid.Nil, errors.New("user not found")
}
