// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: feedback_service.proto

package feedback

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FeedbackType int32

const (
	FeedbackType_FEEDBACK_GENERAL         FeedbackType = 0
	FeedbackType_FEEDBACK_POST            FeedbackType = 1
	FeedbackType_FEEDBACK_MESSENGER       FeedbackType = 2
	FeedbackType_FEEDBACK_RECOMMENDATIONS FeedbackType = 3
	FeedbackType_FEEDBACK_PROFILE         FeedbackType = 4
	FeedbackType_FEEDBACK_AUTH            FeedbackType = 5
)

// Enum value maps for FeedbackType.
var (
	FeedbackType_name = map[int32]string{
		0: "FEEDBACK_GENERAL",
		1: "FEEDBACK_POST",
		2: "FEEDBACK_MESSENGER",
		3: "FEEDBACK_RECOMMENDATIONS",
		4: "FEEDBACK_PROFILE",
		5: "FEEDBACK_AUTH",
	}
	FeedbackType_value = map[string]int32{
		"FEEDBACK_GENERAL":         0,
		"FEEDBACK_POST":            1,
		"FEEDBACK_MESSENGER":       2,
		"FEEDBACK_RECOMMENDATIONS": 3,
		"FEEDBACK_PROFILE":         4,
		"FEEDBACK_AUTH":            5,
	}
)

func (x FeedbackType) Enum() *FeedbackType {
	p := new(FeedbackType)
	*p = x
	return p
}

func (x FeedbackType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FeedbackType) Descriptor() protoreflect.EnumDescriptor {
	return file_feedback_service_proto_enumTypes[0].Descriptor()
}

func (FeedbackType) Type() protoreflect.EnumType {
	return &file_feedback_service_proto_enumTypes[0]
}

func (x FeedbackType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FeedbackType.Descriptor instead.
func (FeedbackType) EnumDescriptor() ([]byte, []int) {
	return file_feedback_service_proto_rawDescGZIP(), []int{0}
}

type Feedback struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Rating       int32                  `protobuf:"varint,2,opt,name=rating,proto3" json:"rating,omitempty"`
	RespondentId string                 `protobuf:"bytes,3,opt,name=respondent_id,json=respondentId,proto3" json:"respondent_id,omitempty"`
	Text         string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Type         FeedbackType           `protobuf:"varint,5,opt,name=type,proto3,enum=file_service.FeedbackType" json:"type,omitempty"`
	CreatedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *Feedback) Reset() {
	*x = Feedback{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feedback_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Feedback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feedback) ProtoMessage() {}

func (x *Feedback) ProtoReflect() protoreflect.Message {
	mi := &file_feedback_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Feedback.ProtoReflect.Descriptor instead.
func (*Feedback) Descriptor() ([]byte, []int) {
	return file_feedback_service_proto_rawDescGZIP(), []int{0}
}

func (x *Feedback) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Feedback) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Feedback) GetRespondentId() string {
	if x != nil {
		return x.RespondentId
	}
	return ""
}

func (x *Feedback) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Feedback) GetType() FeedbackType {
	if x != nil {
		return x.Type
	}
	return FeedbackType_FEEDBACK_GENERAL
}

func (x *Feedback) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type AverageStat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FeedbackId string  `protobuf:"bytes,1,opt,name=feedback_id,json=feedbackId,proto3" json:"feedback_id,omitempty"`
	Average    float32 `protobuf:"fixed32,2,opt,name=average,proto3" json:"average,omitempty"`
}

func (x *AverageStat) Reset() {
	*x = AverageStat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feedback_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AverageStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AverageStat) ProtoMessage() {}

func (x *AverageStat) ProtoReflect() protoreflect.Message {
	mi := &file_feedback_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AverageStat.ProtoReflect.Descriptor instead.
func (*AverageStat) Descriptor() ([]byte, []int) {
	return file_feedback_service_proto_rawDescGZIP(), []int{1}
}

func (x *AverageStat) GetFeedbackId() string {
	if x != nil {
		return x.FeedbackId
	}
	return ""
}

func (x *AverageStat) GetAverage() float32 {
	if x != nil {
		return x.Average
	}
	return 0
}

type SaveFeedbackRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Feedback *Feedback `protobuf:"bytes,1,opt,name=feedback,proto3" json:"feedback,omitempty"`
}

func (x *SaveFeedbackRequest) Reset() {
	*x = SaveFeedbackRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feedback_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveFeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveFeedbackRequest) ProtoMessage() {}

func (x *SaveFeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feedback_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveFeedbackRequest.ProtoReflect.Descriptor instead.
func (*SaveFeedbackRequest) Descriptor() ([]byte, []int) {
	return file_feedback_service_proto_rawDescGZIP(), []int{2}
}

func (x *SaveFeedbackRequest) GetFeedback() *Feedback {
	if x != nil {
		return x.Feedback
	}
	return nil
}

type SaveFeedbackResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *SaveFeedbackResponse) Reset() {
	*x = SaveFeedbackResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feedback_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveFeedbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveFeedbackResponse) ProtoMessage() {}

func (x *SaveFeedbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feedback_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveFeedbackResponse.ProtoReflect.Descriptor instead.
func (*SaveFeedbackResponse) Descriptor() ([]byte, []int) {
	return file_feedback_service_proto_rawDescGZIP(), []int{3}
}

func (x *SaveFeedbackResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetAllFeedbackTypeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  FeedbackType           `protobuf:"varint,1,opt,name=type,proto3,enum=file_service.FeedbackType" json:"type,omitempty"`
	Ts    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=ts,proto3" json:"ts,omitempty"`
	Count int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *GetAllFeedbackTypeRequest) Reset() {
	*x = GetAllFeedbackTypeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feedback_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllFeedbackTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllFeedbackTypeRequest) ProtoMessage() {}

func (x *GetAllFeedbackTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feedback_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllFeedbackTypeRequest.ProtoReflect.Descriptor instead.
func (*GetAllFeedbackTypeRequest) Descriptor() ([]byte, []int) {
	return file_feedback_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllFeedbackTypeRequest) GetType() FeedbackType {
	if x != nil {
		return x.Type
	}
	return FeedbackType_FEEDBACK_GENERAL
}

func (x *GetAllFeedbackTypeRequest) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *GetAllFeedbackTypeRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetAllFeedbackTypeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Feedback []*Feedback `protobuf:"bytes,1,rep,name=feedback,proto3" json:"feedback,omitempty"`
}

func (x *GetAllFeedbackTypeResponse) Reset() {
	*x = GetAllFeedbackTypeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feedback_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllFeedbackTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllFeedbackTypeResponse) ProtoMessage() {}

func (x *GetAllFeedbackTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feedback_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllFeedbackTypeResponse.ProtoReflect.Descriptor instead.
func (*GetAllFeedbackTypeResponse) Descriptor() ([]byte, []int) {
	return file_feedback_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetAllFeedbackTypeResponse) GetFeedback() []*Feedback {
	if x != nil {
		return x.Feedback
	}
	return nil
}

var File_feedback_service_proto protoreflect.FileDescriptor

var file_feedback_service_proto_rawDesc = []byte{
	0x0a, 0x16, 0x66, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd6, 0x01, 0x0a, 0x08, 0x46, 0x65, 0x65, 0x64,
	0x62, 0x61, 0x63, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x23, 0x0a, 0x0d,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x22, 0x48, 0x0a, 0x0b, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x12,
	0x1f, 0x0a, 0x0b, 0x66, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x49, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x07, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x22, 0x49, 0x0a, 0x13, 0x53, 0x61,
	0x76, 0x65, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x32, 0x0a, 0x08, 0x66, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x08, 0x66, 0x65, 0x65,
	0x64, 0x62, 0x61, 0x63, 0x6b, 0x22, 0x30, 0x0a, 0x14, 0x53, 0x61, 0x76, 0x65, 0x46, 0x65, 0x65,
	0x64, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x8d, 0x01, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x50, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x08, 0x66, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63,
	0x6b, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x52,
	0x08, 0x66, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x2a, 0x96, 0x01, 0x0a, 0x0c, 0x46, 0x65,
	0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x46, 0x45,
	0x45, 0x44, 0x42, 0x41, 0x43, 0x4b, 0x5f, 0x47, 0x45, 0x4e, 0x45, 0x52, 0x41, 0x4c, 0x10, 0x00,
	0x12, 0x11, 0x0a, 0x0d, 0x46, 0x45, 0x45, 0x44, 0x42, 0x41, 0x43, 0x4b, 0x5f, 0x50, 0x4f, 0x53,
	0x54, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x46, 0x45, 0x45, 0x44, 0x42, 0x41, 0x43, 0x4b, 0x5f,
	0x4d, 0x45, 0x53, 0x53, 0x45, 0x4e, 0x47, 0x45, 0x52, 0x10, 0x02, 0x12, 0x1c, 0x0a, 0x18, 0x46,
	0x45, 0x45, 0x44, 0x42, 0x41, 0x43, 0x4b, 0x5f, 0x52, 0x45, 0x43, 0x4f, 0x4d, 0x4d, 0x45, 0x4e,
	0x44, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x53, 0x10, 0x03, 0x12, 0x14, 0x0a, 0x10, 0x46, 0x45, 0x45,
	0x44, 0x42, 0x41, 0x43, 0x4b, 0x5f, 0x50, 0x52, 0x4f, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x04, 0x12,
	0x11, 0x0a, 0x0d, 0x46, 0x45, 0x45, 0x44, 0x42, 0x41, 0x43, 0x4b, 0x5f, 0x41, 0x55, 0x54, 0x48,
	0x10, 0x05, 0x32, 0xd1, 0x01, 0x0a, 0x0f, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x55, 0x0a, 0x0c, 0x53, 0x61, 0x76, 0x65, 0x46, 0x65,
	0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x21, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61,
	0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x66, 0x69, 0x6c, 0x65,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x46, 0x65, 0x65,
	0x64, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x67, 0x0a,
	0x12, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x27, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63,
	0x6b, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x66,
	0x69, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x21, 0x5a, 0x1f, 0x71, 0x75, 0x69, 0x63, 0x6b, 0x66,
	0x6c, 0x6f, 0x77, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x66, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_feedback_service_proto_rawDescOnce sync.Once
	file_feedback_service_proto_rawDescData = file_feedback_service_proto_rawDesc
)

func file_feedback_service_proto_rawDescGZIP() []byte {
	file_feedback_service_proto_rawDescOnce.Do(func() {
		file_feedback_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_feedback_service_proto_rawDescData)
	})
	return file_feedback_service_proto_rawDescData
}

var file_feedback_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_feedback_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_feedback_service_proto_goTypes = []interface{}{
	(FeedbackType)(0),                  // 0: file_service.FeedbackType
	(*Feedback)(nil),                   // 1: file_service.Feedback
	(*AverageStat)(nil),                // 2: file_service.AverageStat
	(*SaveFeedbackRequest)(nil),        // 3: file_service.SaveFeedbackRequest
	(*SaveFeedbackResponse)(nil),       // 4: file_service.SaveFeedbackResponse
	(*GetAllFeedbackTypeRequest)(nil),  // 5: file_service.GetAllFeedbackTypeRequest
	(*GetAllFeedbackTypeResponse)(nil), // 6: file_service.GetAllFeedbackTypeResponse
	(*timestamppb.Timestamp)(nil),      // 7: google.protobuf.Timestamp
}
var file_feedback_service_proto_depIdxs = []int32{
	0, // 0: file_service.Feedback.type:type_name -> file_service.FeedbackType
	7, // 1: file_service.Feedback.created_at:type_name -> google.protobuf.Timestamp
	1, // 2: file_service.SaveFeedbackRequest.feedback:type_name -> file_service.Feedback
	0, // 3: file_service.GetAllFeedbackTypeRequest.type:type_name -> file_service.FeedbackType
	7, // 4: file_service.GetAllFeedbackTypeRequest.ts:type_name -> google.protobuf.Timestamp
	1, // 5: file_service.GetAllFeedbackTypeResponse.feedback:type_name -> file_service.Feedback
	3, // 6: file_service.FeedbackService.SaveFeedback:input_type -> file_service.SaveFeedbackRequest
	5, // 7: file_service.FeedbackService.GetAllFeedbackType:input_type -> file_service.GetAllFeedbackTypeRequest
	4, // 8: file_service.FeedbackService.SaveFeedback:output_type -> file_service.SaveFeedbackResponse
	6, // 9: file_service.FeedbackService.GetAllFeedbackType:output_type -> file_service.GetAllFeedbackTypeResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_feedback_service_proto_init() }
func file_feedback_service_proto_init() {
	if File_feedback_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_feedback_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Feedback); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_feedback_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AverageStat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_feedback_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveFeedbackRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_feedback_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveFeedbackResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_feedback_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllFeedbackTypeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_feedback_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllFeedbackTypeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_feedback_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_feedback_service_proto_goTypes,
		DependencyIndexes: file_feedback_service_proto_depIdxs,
		EnumInfos:         file_feedback_service_proto_enumTypes,
		MessageInfos:      file_feedback_service_proto_msgTypes,
	}.Build()
	File_feedback_service_proto = out.File
	file_feedback_service_proto_rawDesc = nil
	file_feedback_service_proto_goTypes = nil
	file_feedback_service_proto_depIdxs = nil
}
