// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package feedback

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FeedbackServiceClient is the client API for FeedbackService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FeedbackServiceClient interface {
	SaveFeedback(ctx context.Context, in *SaveFeedbackRequest, opts ...grpc.CallOption) (*SaveFeedbackResponse, error)
	GetAllFeedbackType(ctx context.Context, in *GetAllFeedbackTypeRequest, opts ...grpc.CallOption) (*GetAllFeedbackTypeResponse, error)
	GetNumMessagesSent(ctx context.Context, in *GetNumMessagesSentRequest, opts ...grpc.CallOption) (*GetNumMessagesSentResponse, error)
	GetNumPostsCreated(ctx context.Context, in *GetNumPostsCreatedRequest, opts ...grpc.CallOption) (*GetNumPostsCreatedResponse, error)
	GetNumProfileChanges(ctx context.Context, in *GetNumProfileChangesRequest, opts ...grpc.CallOption) (*GetNumProfileChangesResponse, error)
}

type feedbackServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFeedbackServiceClient(cc grpc.ClientConnInterface) FeedbackServiceClient {
	return &feedbackServiceClient{cc}
}

func (c *feedbackServiceClient) SaveFeedback(ctx context.Context, in *SaveFeedbackRequest, opts ...grpc.CallOption) (*SaveFeedbackResponse, error) {
	out := new(SaveFeedbackResponse)
	err := c.cc.Invoke(ctx, "/file_service.FeedbackService/SaveFeedback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedbackServiceClient) GetAllFeedbackType(ctx context.Context, in *GetAllFeedbackTypeRequest, opts ...grpc.CallOption) (*GetAllFeedbackTypeResponse, error) {
	out := new(GetAllFeedbackTypeResponse)
	err := c.cc.Invoke(ctx, "/file_service.FeedbackService/GetAllFeedbackType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedbackServiceClient) GetNumMessagesSent(ctx context.Context, in *GetNumMessagesSentRequest, opts ...grpc.CallOption) (*GetNumMessagesSentResponse, error) {
	out := new(GetNumMessagesSentResponse)
	err := c.cc.Invoke(ctx, "/file_service.FeedbackService/GetNumMessagesSent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedbackServiceClient) GetNumPostsCreated(ctx context.Context, in *GetNumPostsCreatedRequest, opts ...grpc.CallOption) (*GetNumPostsCreatedResponse, error) {
	out := new(GetNumPostsCreatedResponse)
	err := c.cc.Invoke(ctx, "/file_service.FeedbackService/GetNumPostsCreated", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedbackServiceClient) GetNumProfileChanges(ctx context.Context, in *GetNumProfileChangesRequest, opts ...grpc.CallOption) (*GetNumProfileChangesResponse, error) {
	out := new(GetNumProfileChangesResponse)
	err := c.cc.Invoke(ctx, "/file_service.FeedbackService/GetNumProfileChanges", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FeedbackServiceServer is the server API for FeedbackService service.
// All implementations must embed UnimplementedFeedbackServiceServer
// for forward compatibility
type FeedbackServiceServer interface {
	SaveFeedback(context.Context, *SaveFeedbackRequest) (*SaveFeedbackResponse, error)
	GetAllFeedbackType(context.Context, *GetAllFeedbackTypeRequest) (*GetAllFeedbackTypeResponse, error)
	GetNumMessagesSent(context.Context, *GetNumMessagesSentRequest) (*GetNumMessagesSentResponse, error)
	GetNumPostsCreated(context.Context, *GetNumPostsCreatedRequest) (*GetNumPostsCreatedResponse, error)
	GetNumProfileChanges(context.Context, *GetNumProfileChangesRequest) (*GetNumProfileChangesResponse, error)
	mustEmbedUnimplementedFeedbackServiceServer()
}

// UnimplementedFeedbackServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFeedbackServiceServer struct {
}

func (UnimplementedFeedbackServiceServer) SaveFeedback(context.Context, *SaveFeedbackRequest) (*SaveFeedbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveFeedback not implemented")
}
func (UnimplementedFeedbackServiceServer) GetAllFeedbackType(context.Context, *GetAllFeedbackTypeRequest) (*GetAllFeedbackTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllFeedbackType not implemented")
}
func (UnimplementedFeedbackServiceServer) GetNumMessagesSent(context.Context, *GetNumMessagesSentRequest) (*GetNumMessagesSentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNumMessagesSent not implemented")
}
func (UnimplementedFeedbackServiceServer) GetNumPostsCreated(context.Context, *GetNumPostsCreatedRequest) (*GetNumPostsCreatedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNumPostsCreated not implemented")
}
func (UnimplementedFeedbackServiceServer) GetNumProfileChanges(context.Context, *GetNumProfileChangesRequest) (*GetNumProfileChangesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNumProfileChanges not implemented")
}
func (UnimplementedFeedbackServiceServer) mustEmbedUnimplementedFeedbackServiceServer() {}

// UnsafeFeedbackServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FeedbackServiceServer will
// result in compilation errors.
type UnsafeFeedbackServiceServer interface {
	mustEmbedUnimplementedFeedbackServiceServer()
}

func RegisterFeedbackServiceServer(s grpc.ServiceRegistrar, srv FeedbackServiceServer) {
	s.RegisterService(&FeedbackService_ServiceDesc, srv)
}

func _FeedbackService_SaveFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedbackServiceServer).SaveFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file_service.FeedbackService/SaveFeedback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedbackServiceServer).SaveFeedback(ctx, req.(*SaveFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedbackService_GetAllFeedbackType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllFeedbackTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedbackServiceServer).GetAllFeedbackType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file_service.FeedbackService/GetAllFeedbackType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedbackServiceServer).GetAllFeedbackType(ctx, req.(*GetAllFeedbackTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedbackService_GetNumMessagesSent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNumMessagesSentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedbackServiceServer).GetNumMessagesSent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file_service.FeedbackService/GetNumMessagesSent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedbackServiceServer).GetNumMessagesSent(ctx, req.(*GetNumMessagesSentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedbackService_GetNumPostsCreated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNumPostsCreatedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedbackServiceServer).GetNumPostsCreated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file_service.FeedbackService/GetNumPostsCreated",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedbackServiceServer).GetNumPostsCreated(ctx, req.(*GetNumPostsCreatedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedbackService_GetNumProfileChanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNumProfileChangesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedbackServiceServer).GetNumProfileChanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file_service.FeedbackService/GetNumProfileChanges",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedbackServiceServer).GetNumProfileChanges(ctx, req.(*GetNumProfileChangesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FeedbackService_ServiceDesc is the grpc.ServiceDesc for FeedbackService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FeedbackService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "file_service.FeedbackService",
	HandlerType: (*FeedbackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveFeedback",
			Handler:    _FeedbackService_SaveFeedback_Handler,
		},
		{
			MethodName: "GetAllFeedbackType",
			Handler:    _FeedbackService_GetAllFeedbackType_Handler,
		},
		{
			MethodName: "GetNumMessagesSent",
			Handler:    _FeedbackService_GetNumMessagesSent_Handler,
		},
		{
			MethodName: "GetNumPostsCreated",
			Handler:    _FeedbackService_GetNumPostsCreated_Handler,
		},
		{
			MethodName: "GetNumProfileChanges",
			Handler:    _FeedbackService_GetNumProfileChanges_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "feedback_service.proto",
}
